config/routes.rb
JkliuProj2::Application.routes.draw do
  match '/register' => 'users#new', :as => :register
  
  resources :users
  resources :sessions
  
  match '/login' => 'sessions#new', :as => :login
  match '/logout' => 'sessions#destroy', :as => :logout

  resources :products do
    member do
      get 'add_to_cart'
    end
  end

  match '/items/edit' => 'items#edit', :as => :edit_item, :via => :post
  match '/items/:id/remove' => 'items#remove', :as => :remove_item, :via => :get

  match '/carts/current' => 'carts#view_current', :as => :current_cart, :via => :get
  match '/carts/saved' => 'carts#view_saved', :as => :saved_carts, :via => :get
  
  match '/carts/:id/checkout' => 'carts#checkout', :as => :checkout
  match '/carts/:id/review' => 'carts#review', :as => :review_cart
  match '/carts/:id/save' => 'carts#save', :as => :save_cart
  match '/carts/:id/activate' => 'carts#activate', :as => :activate_cart
  
  match '/orders' => 'orders#create', :as => :place_order

  match '/admin' => 'orders#show'
  match '/admin/orders' => 'orders#show', :as => :admin_orders
  match '/admin/products' => 'products#admin_view', :as => :admin_products

  root :to => 'products#index'
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :items
  belongs_to :user
  has_one :order
  attr_accessible :status, :user_id

  # attaches cart to user
  # requires: param user_id is defined
  # modifies: user_id
  # effects: create association between cart and user
  def attach_to_user(user_id)
  	self.user_id = user_id
  	self.save
  end

  # returns the total quantity of all items in the cart
  def get_total_qty
    return self.items.sum(:qty)
  end

  # returns a list of items in the cart whose prices have changed
  # since they were added to the cart, or since the cart was last viewed
  # modifies: price of each item in cart, if associated product's price has changed
  # effects: updates prices of items to match products
  def get_price_changes
  	changed_products = []
  	self.items.each do |item|
  	 	if item.price_has_changed
  			item.update_price
			  changed_products.push item.product
		  end
	  end
	  return changed_products
  end

  # saves cart so that it can be re-activated later
  def save_cart
  	self.status = 'saved'
  	self.save
  end

  # activates cart (to be displayed in upper corner, so user
  #  can add and remove items from it)
  def activate
    self.status = 'current'
    self.save
  end

  # sets status of cart to 'ordered'
  def set_to_ordered
    self.status = "ordered"
    self.save
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	include CartsHelper
	before_filter :require_user_login, :only => [:view_saved, :save, :activate, :checkout, :review]
	before_filter :verify_ownership, :only => [:save, :activate, :checkout, :review]
	

	# GET /carts/current
	# display items in current cart
	def view_current
		if @current_cart
			@items = Cart.find(cookies[:cart_id]).items
			display_price_changes(@current_cart.id)
		else
			flash.now[:notice] = "You have 0 items in your cart. Start shopping!"
		end
	end

	# GET /carts/saved
	# show all saved carts
	# requires: user is logged in
	def view_saved
		@carts = Cart.where(:user_id => @current_user.id, :status => 'saved')
		if @carts.empty?
			flash.now[:notice] = "You do not have any saved carts."
		end
	end

	# GET /carts/1/save
	# requires: user is logged in, @cart belongs to user,
	# 			@cart.status = "current", @cart is not empty
	# modifies: @cart
	# effects: @cart.status = "saved"
	def save
		@cart = Cart.find(params[:id])
		@cart.save_cart
		cookies.delete :cart_id
		flash.now[:notice] = "Your cart has been saved."
		redirect_to saved_carts_url
	end

	# GET /carts/1/activate
	# requires: user is logged in, @cart belongs to user,
	# 			@cart.status = "saved"
	# modifies: @cart, @current_cart
	# effects:
	# => saves current cart, if there is currently one active
	# => activates specified cart by setting status to "current"
	def activate
		if @current_cart
  	   		@current_cart.save_cart
    	end
		@cart = Cart.find_by_id(params[:id])
		@cart.activate
		cookies[:cart_id] = @cart.id
		redirect_to current_cart_url
	end

	# GET carts/1/checkout
	# prompts user to select a shipping address
	def checkout
		if cookies[:user_id]
			@addresses = User.find(cookies[:user_id]).addresses
			# TODO: take this out and implement checkout.html page w/address
			redirect_to review_url
		end
	end

	# GET carts/1/review
	# summarizes order before user confirms
	def review
		@cart = Cart.find_by_id(params[:id])
		if @cart.user_id == nil
			@cart.attach_to_user(@current_user.id)
		end
		display_price_changes(@cart.id)
		@items = @cart.items
		# TODO: incorporate address
		# @address = Address.find(params[:address_id])
	end

end

app/helpers/carts_helper.rb
module CartsHelper
	# checks if prices of items have changed, and if so, constructs bulleted flash
	# message for user
	# requires: cart_id is a valid cart id
	# modifies: prices of each item in cart, if associated product's price has changed
	# effects: updates price of each item in cart
	def display_price_changes(cart_id)
		cart = Cart.find_by_id(cart_id)
		changed_products = cart.get_price_changes
		if changed_products.length > 0
			msg = "The following items in your cart have a new price: <ul>"
			changed_products.each do |product|
				msg += "<li>" + product.name + " is now $" + product.price.to_s + "</li>"
			end
			msg += "</ul>"
			flash.now[:notice] = msg.html_safe
		end
	end

	# checks if logged-in user owns the cart provided in the url
	# if not, displays 403 error page
	def verify_ownership
		if @current_user.id != Cart.find(params[:id]).user.id
			flash.now[:error] = "Oops! You do not have permission to view this page."
			render :file => File.join(Rails.root, 'public', '403.html'), 
             	   :status => 403
		end
	end
end

app/views/carts/review.html.erb
<h1>Review your order</h1>

<table class="table">
	<tr>
		<th>Name</th>
		<th>Price</th>
		<th>Quantity</th>
	</tr>

	<% @items.each do |item| %>
	<tr>
		<td><%= item.product.name %></td>
		<td>$ <%= number_with_precision item.price, :precision => 2 %></td>
		<td><%= item.qty %></td>
	</tr>
	<% end %>
</table>

<%= button_to 'Edit cart', current_cart_path, :class => "btn", :method => :get %>

<%= button_to 'Place your order', place_order_path(:cart_id => @cart.id), :class => "btn" %>

app/views/carts/view_current.html.erb
<% content_for :heading do %>
    Your cart
<% end %>

<%= link_to "View saved carts", saved_carts_path %>

<% if @items %>
	<table class="table">
		<tr>
			<th>Name</th>
			<th>Price</th>
			<th>Quantity</th>
			<th></th>
		</tr>
		
			<% @items.each do |item| %>
			<tr>
				<td><%= item.product.name %></td>
				<td>$ <%= number_with_precision item.price, :precision => 2 %></td>
				<td>
					<%= form_tag(edit_item_path, :method => "post", :class => "form-inline") do %>
						<%= hidden_field_tag(:id, item.id) %>
						<%= select_tag(:qty, options_for_select([[1,1], [2,2], [3,3], [4,4], [5,5]], item.qty), :class => "span1") %>
						<%= button_tag 'Update', :class => "btn btn-small" %>
					<% end %> 
				</td>
				<td>
					<%= button_to 'Remove', remove_item_path(item), :class => "btn btn-small", :method => :get %>

				</td>
			</tr>
			<% end %>
		
	</table>
	<%= button_to 'Save this cart', save_cart_path(@current_cart), :class => "btn btn-inverse", :method => :get %>
	<%= button_to 'Proceed to checkout', review_cart_path(@current_cart), :class => "btn btn-primary", :method => :get %>
<% end %>

app/views/carts/view_saved.html.erb
<% content_for :heading do %>
    Your saved carts
<% end %>

<% if @carts %>
	<% @carts.each do |cart| %>
	<div class ="cart_contents">
		Cart
		</ul>
			<% cart.items.each do |item| %>
				<li><%= item.product.name %> x <%= item.qty %></li>
			<% end %>
		</ul>
	</div>
	<div class="cart_options">
		<%= button_to 'Shop with this cart', activate_cart_path(cart), :class => 'btn btn-inverse', :method => :get %>
		<%= button_to 'Checkout', review_cart_path(cart), :class => "btn btn-primary", :method => :get %>
	<% end %>
<% end %>