config/routes.rb
JkliuProj2::Application.routes.draw do
  match '/register' => 'users#new', :as => :register
  
  resources :users
  resources :sessions
  
  match '/login' => 'sessions#new', :as => :login
  match '/logout' => 'sessions#destroy', :as => :logout

  resources :products do
    member do
      get 'add_to_cart'
    end
  end

  match '/items/edit' => 'items#edit', :as => :edit_item, :via => :post
  match '/items/:id/remove' => 'items#remove', :as => :remove_item, :via => :get

  match '/carts/current' => 'carts#view_current', :as => :current_cart, :via => :get
  match '/carts/saved' => 'carts#view_saved', :as => :saved_carts, :via => :get
  
  match '/carts/:id/checkout' => 'carts#checkout', :as => :checkout
  match '/carts/:id/review' => 'carts#review', :as => :review_cart
  match '/carts/:id/save' => 'carts#save', :as => :save_cart
  match '/carts/:id/activate' => 'carts#activate', :as => :activate_cart
  
  match '/orders' => 'orders#create', :as => :place_order

  match '/admin' => 'orders#show'
  match '/admin/orders' => 'orders#show', :as => :admin_orders
  match '/admin/products' => 'products#admin_view', :as => :admin_products

  root :to => 'products#index'
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :items
  validates_presence_of :name, :price, :qty_in_stock
  attr_accessible :brand, :info, :name, :price, :qty_in_stock, :items

  # check if product has at least [qty] in stock
  def has_in_stock(qty)
  	if self.qty_in_stock >= qty
  		return true
  	else
  		return false
  	end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :require_admin_auth, :only => [:admin_view, :new, :edit, :create, :udpate, :destroy]
  layout "admin", :only => [:admin_view, :new, :edit, :update, :destroy]
  
  # GET /products
  # GET /products.json
  # display product catalog for shoppers
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/admin
  # display product information for admin
  # requires: admin is logged in
  def admin_view
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  # display information for individual product
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  # display form to create a new product
  # requires: Admin is logged in
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  # displays form to edit product
  # requires: Admin is logged in, product with id exists
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  # requires: Admin is logged in, :product param is defined
  # modifies: products (if validation passes)
  # effects: new product is created (if validation passes)
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to admin_products_url, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else # save fails due to validation error -> show errors
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  # requires: Admin is logged in, product with id exists
  # modifies: product
  # effects: product is updated with new attributes, else errors are displayed
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to admin_products_url, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else # update fails due to validation error -> show errors
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  # requires: Admin is logged in, product with id exists
  # modifies: products
  # effects: deletes product from catalog
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to admin_products_url, notice: 'Product has been deleted.' }
      format.json { head :no_content }
    end
  end


  # GET /products/1/add_to_cart
  # adds 1 of product to cart, or alerts user if product is out of stock
  # requires: product with id exists
  # modifies: cart, product (if product in stock)
  # effects:
  # => if product is in stock:
  # =>    identifies cart if it exists in session, otherwise creates new one
  # =>    if product is already in the cart, increment the quantity
  # =>    otherwise create a new Item object with quantity 1 associated with this cart
  def add_to_cart
    @product = Product.find(params[:id])
    # alert user if product is out of stock
    if @product.qty_in_stock == 0
      flash[:notice] = "Sorry, " + @product.name + " is currently out of stock. Please check back soon!"
    else
      # check if a cart already exists in the session
      if cookies[:cart_id]
        @cart = Cart.find_by_id(cookies[:cart_id])
      else # if not, create a new cart
        @cart = Cart.create(:status => 'current')
        cookies[:cart_id] = @cart.id
        # if user is logged in, associate cart with that user
        if logged_in?
          @cart.attach_to_user(@current_user.id)
        end
      end
        
      # check if item already exists in cart      
      @item = @cart.items.where(:product_id => @product.id).first
      if @item.blank? #if not, create a new item
        @item = @cart.items.create(:product_id => @product.id, :name => @product.name, 
          :price => @product.price, :qty => 0)
      end
      @item.add

      # TODO: give the cookie an expiration date so that the product can be restored if not bought?
      flash[:notice] = @product.name + " has been added to your cart."
    end
    # stay in the same view
    redirect_to :controller => 'products', :action => 'show', :id => @product.id
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
    <div class="field">
    <%= f.label :brand %><br />
    <%= f.text_field :brand %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    $ <%= f.text_field :price, :precision => 2 %>
  </div>

  <div class="field">
    <%= f.label :qty_in_stock %><br />
    <%= f.text_field :qty_in_stock %>
  </div>
  <div class="field">
    <%= f.label :info %><br />
    <%= f.text_area :info %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/admin_view.html.erb
<% content_for :heading do %>
    Products
<% end %>

<table class="table">
  <tr>
    <th>Name</th>
    
    <th>Brand</th>
    <th>Price</th>
    <th>Qty in stock</th>
    <th>Info</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= product.brand %></td>
    <td>$<%= number_with_precision product.price, :precision => 2 %></td>
    
    <td><%= product.qty_in_stock %></td>
    <td><%= product.info %></td>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_product_path %>

app/views/products/edit.html.erb
<% content_for :heading do %>
    Edit product
<% end %>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Welcome</h1>
Check out our latest products!
<table class="table">
  <tr>
    <th>Product</th>
    <th>Info</th>
    <th>Price</th>


  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= link_to product.name, product %> by <%= product.brand %></td>
    <td><%= product.info %></td>
    <td>$<%= number_with_precision product.price, :precision => 2 %></td>
    

  </tr>
<% end %>
</table>

<br />

app/views/products/new.html.erb
<% content_for :heading do %>
    Add a new product
<% end %>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Price:</b>
   $<%= number_with_precision @product.price, :precision => 2 %>
</p>

<p>
  <b>Brand:</b>
  <%= @product.brand %>
</p>

<p>
  <b>Qty:</b>
  <%= @product.qty_in_stock %>
</p>

<p>
  <b>Info:</b>
  <%= @product.info %>
</p>

<%= button_to 'Add to Cart', add_to_cart_product_path(@product), :class => "btn btn-primary", :method => :get %>


<%= link_to 'Back', products_path %>