config/routes.rb
JkliuProj2::Application.routes.draw do
  match '/register' => 'users#new', :as => :register
  
  resources :users
  resources :sessions
  
  match '/login' => 'sessions#new', :as => :login
  match '/logout' => 'sessions#destroy', :as => :logout

  resources :products do
    member do
      get 'add_to_cart'
    end
  end

  match '/items/edit' => 'items#edit', :as => :edit_item, :via => :post
  match '/items/:id/remove' => 'items#remove', :as => :remove_item, :via => :get

  match '/carts/current' => 'carts#view_current', :as => :current_cart, :via => :get
  match '/carts/saved' => 'carts#view_saved', :as => :saved_carts, :via => :get
  
  match '/carts/:id/checkout' => 'carts#checkout', :as => :checkout
  match '/carts/:id/review' => 'carts#review', :as => :review_cart
  match '/carts/:id/save' => 'carts#save', :as => :save_cart
  match '/carts/:id/activate' => 'carts#activate', :as => :activate_cart
  
  match '/orders' => 'orders#create', :as => :place_order

  match '/admin' => 'orders#show'
  match '/admin/orders' => 'orders#show', :as => :admin_orders
  match '/admin/products' => 'products#admin_view', :as => :admin_products

  root :to => 'products#index'
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>J-Cart</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
	<div class="navbar navbar-inverse">
		<div class="navbar-inner">
			<a class="brand" href="#">J-Cart Admin</a>
			<div class="pull-right">

				<ul class="nav">
					<li id="products"><%= link_to 'Orders', admin_orders_path %></li>
					<li id="products"><%= link_to 'Products', admin_products_path %></li>
				</ul>
				<% if logged_in? %>
					<%= link_to logout_path, :class => "btn", do %>
						Log out
					<% end %>
				<% end %>
			</div>
		</div>
	</div>

	<% if notice %>
	<div class="alert alert-success" id="notice"><%= notice %></div>
	<% end %>

	<% if flash[:error] %>
	<div class="alert alert-error"><%= flash[:error] %></div>
	<% end %>

	<% if @auth_admin %>
		<h1><%= yield :heading %></h1>
		<%= yield %>
	<% else %>
		<%= link_to 'Back', root_path %>
	<% end %>

</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>J-Cart</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
	<div class="navbar navbar-inverse">
		<div class="navbar-inner">

			<%= link_to "J-Cart", root_path, :class => "brand" %>
			<div class="pull-right">
				<% if logged_in? %>
					Welcome, <%= current_user.first_name %>!			
				<% end %>
				<%= link_to current_cart_path, :class => "btn btn-primary", do %>
					<i class="icon-shopping-cart icon-white"></i> Your cart: <%= @cart_qty %>
				<% end %>
				<% if logged_in? %>
					<%= link_to logout_path, :class => "btn", do %>
						Log out
					<% end %>
				<% else %>
					<%= link_to login_path, :class => "btn", do %>
						Log in/Register
					<% end %>
				<% end %>
			</div>
		</div>
	</div>

	<h1><%= yield :heading %></h1>

	<% if notice %>
	<div class="alert alert-success" id="notice"><%= notice %></div>
	<% end %>

	<% if flash[:error] %>
	<div class="alert alert-error"><%= flash[:error] %></div>
	<% end %>

	<%= yield %>
</div>
</body>
</html>